all: serveur1-CodeWarriors serveur2-CodeWarriors serveur3-CodeWarriors 
serveur1-CodeWarriors: serveur1-CodeWarriors.c 
	gcc serveur1-CodeWarriors.c -o serveur1-CodeWarriors -lpthread

serveur2-CodeWarriors: serveur2-CodeWarriors.c 
	gcc serveur2-CodeWarriors.c -o serveur2-CodeWarriors -lpthread

serveur3-CodeWarriors: serveur3-CodeWarriors.c 
	gcc serveur3-CodeWarriors.c -o serveur3-CodeWarriors -lpthread


clean:
	rm -f serveur2-CodeWarriors
	rm -f serveur1-CodeWarriors
	rm: -f serveur3-CodeWarriors
	